name: ci-wasm32

on:
  #push:
  #pull_request:

jobs:

  ci-wasm32:
    name: ci-wasm32
    runs-on: ubuntu-20.04
    steps:

      - name: setup-proot
        run: |
          sudo apt install -y proot

      - name: setup-ghc-wasm32-wasi
        run: |
          pushd $(mktemp -d)
          curl -L https://github.com/tweag/ghc-wasm32-wasi/archive/refs/heads/master.tar.gz | tar xz --strip-components=1
          ./setup.sh
          ~/.ghc-wasm32-wasi/add_to_github_path.sh
          popd

      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: |
          sed -i '/tasty/d' time.cabal

          echo "package QuickCheck" >> cabal.project.local
          echo "  flags: -templatehaskell" >> cabal.project.local

          autoreconf -i

          wasmtime-run wasm32-wasi-cabal run ShowDefaultTZAbbreviations
          wasmtime-run wasm32-wasi-cabal run ShowTime
